# Generated by Django 4.0.5 on 2022-06-03 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='ColdBrew',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='brew',
        ),
        migrations.RemoveField(
            model_name='category',
            name='espresso',
        ),
    ]
