# Generated by Django 4.0.6 on 2022-07-22 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'business_areas',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('salary', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.company')),
            ],
            options={
                'db_table': 'job_posts',
            },
        ),
        migrations.CreateModel(
            name='JobPostSkillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'job_types',
            },
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('job_posts', models.ManyToManyField(through='post.JobPostSkillSet', to='post.jobpost')),
            ],
            options={
                'db_table': 'skill_sets',
            },
        ),
        migrations.AddField(
            model_name='jobpostskillset',
            name='skill_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.skillset'),
        ),
        migrations.CreateModel(
            name='JobPostActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
                ('job_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.jobpost')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_post_activity',
            },
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.jobtype'),
        ),
        migrations.CreateModel(
            name='CompanyBusinessArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.businessarea')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.company')),
            ],
            options={
                'db_table': 'company_business_areas',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='business_area',
            field=models.ManyToManyField(through='post.CompanyBusinessArea', to='post.businessarea'),
        ),
    ]
